"""sync nullables

Revision ID: 263108d18172
Revises:
Create Date: 2025-10-17 03:47:33.694639

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "263108d18172"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_keys") as batch:
        batch.alter_column("key", existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table("tell_messages") as batch:
        batch.alter_column("conn", existing_type=sa.VARCHAR(), nullable=True)
        batch.alter_column("sender", existing_type=sa.VARCHAR(), nullable=True)
        batch.alter_column("target", existing_type=sa.VARCHAR(), nullable=True)
        batch.alter_column("message", existing_type=sa.VARCHAR(), nullable=True)
        batch.alter_column("is_read", existing_type=sa.BOOLEAN(), nullable=True)
        batch.alter_column(
            "time_sent", existing_type=sa.DATETIME(), nullable=True
        )
        batch.alter_column(
            "time_read", existing_type=sa.DATETIME(), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tell_messages") as batch:
        batch.alter_column(
            "time_read", existing_type=sa.DATETIME(), nullable=False
        )
        batch.alter_column(
            "time_sent", existing_type=sa.DATETIME(), nullable=False
        )
        batch.alter_column(
            "is_read", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch.alter_column(
            "message", existing_type=sa.VARCHAR(), nullable=False
        )
        batch.alter_column("target", existing_type=sa.VARCHAR(), nullable=False)
        batch.alter_column("sender", existing_type=sa.VARCHAR(), nullable=False)
        batch.alter_column("conn", existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table("channel_keys") as batch:
        batch.alter_column("key", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
